version: '2'
services:
    currencyapi:
        build:
          context: .
          dockerfile: Dockerfile
        working_dir: /var/www/
        command: php -S 0.0.0.0:7000 -t public index.php
        environment:
            docker: "true"
        ports:
            - 8001:7000
        volumes:
            - .:/var/www
            - /sbin/ip:/sbin/ip
